### ISSUE TITLE
Ripple on press in?

### ISSUE THREAD

**Issue by Noitidart** [n4kz/react-native-material-ripple#12]
In Android I think its standard to start the ripple in `onPressIn` (and remain till `onPressOut`). Is this possible? It seems it is only starting ripple in `onPressOut`. I am not able to pull it off.

Thanks

**Comment by n4kz** [comment]
Thanks for question, please take look at issue #4.

**Comment by Noitidart** [comment]
Oh whoops excuse the dupe.
