### ISSUE TITLE
Child <Ripple> of parent <Ripple> not getting touch event

### ISSUE THREAD

**Issue by Noitidart** [n4kz/react-native-material-ripple#13]
I am trying to have the main card be a `<Ripple>` and then I have some child views that I want `<Ripple>` as well. However on pressing child view, the parent-most `<Ripple>` takes the touch.

Is there a work around for this?

**Comment by n4kz** [comment]
Thanks for question. I see no easy workaround as one of `Ripple` subviews explicitly disables any touch events on child components by setting `pointerEvents='box-only'` prop. I can suggest absolute positioning for biggest ripple with manual activation via `startRipple()` method. Please, take look at my [`Dropdown`](https://github.com/n4kz/react-native-material-dropdown/blob/0a8c84845ea7cdadba3882d90595538333400d9d/src/components/dropdown/index.js#L585) for manual activation example.

**Comment by Noitidart** [comment]
I found that if I use `<TouchableNativeFeedback>` it does allow child `<TouchableNativeFeedback>`s to also ripple. Maybe we can copy what they did?

**Comment by yairopro** [comment]
+1

**Comment by pavelustenko** [comment]
Same question...
Usual React-native touchables do allow to have another touchables inside and don't prevent touches on them.

**Comment by yairopro** [comment]
Well it's an open-source project. You are free to implement a solution you, or waiting someone new, who need this problem to be solved too, to implement it for you.
