### ISSUE TITLE
[QUESTION] Round buttons

### ISSUE THREAD

**Issue by filipef101** [n4kz/react-native-material-ripple#19]
Hello, I have like rounded buttons and the effect does not respect that, rendering as the view is a square, is this fixable?

**Comment by galechus** [comment]
Try to use `rippleContainerBorderRadius` prop.

**Comment by filipef101** [comment]
@galechus Okay, I managed!
But is there any reason it doesn`t use what we pass in the style?

**Comment by galechus** [comment]
@filipef101, could you paste your code?

**Comment by filipef101** [comment]
Ah, I meant the border radius we pass I. The style

**Comment by filipef101** [comment]
In

**Comment by galechus** [comment]
Please paste the code of your component and styles...

**Comment by filipef101** [comment]
Sorry I can't.
But I don't have an issue anymore, was just wondering why we have to pass the border radius on the props
