### ISSUE TITLE
`onPress` has some delay

### ISSUE THREAD

**Issue by aeruhxi** [n4kz/react-native-material-ripple#20]
I noticed that `Ripple`'s `onPress` is called with some delay. I swapped it with `TouchableNativeFeedback` and `TouchableOpacity`; the `onPress` is called in an instant. I also set `rippleDuration` to 0 if that should matter but I guess it shouldn't.

**Comment by abs-zero** [comment]
`onPressIn` and `onPressOut` are fast but they don't start animation.

**Comment by girish54321** [comment]
@aeruhxi But some delay is there and onPressIn calls the function before animation starts don't know how to solve this  
HELP !
