### ISSUE TITLE
How to stop propagation

### ISSUE THREAD

**Issue by jacek213** [n4kz/react-native-material-ripple#23]
Let's say I have a structure like:

    <Ripple onPress={onRipplePress}>
      <TouchableWithoutFeedback onPress={onTouchablePress}>...</TouchableWithoutFeedback>
    </Ripple>

On press of `onTouchablePress` I wouldn't like this event to be propaged to `onRipplePress` (in my specific case). Is that possible?

While using base native Touchable components it's possible by using another `Touchable...` component (described here: https://stackoverflow.com/questions/31866671/how-to-stop-touch-event-propagation-in-react-native)

**Comment by n4kz** [comment]
Thanks for question! Container view inside `Ripple` component has property `pointerEvents` set to `box-only` and children components should not receive any touch events at all. However you can start `Ripple` programmatically by calling `.startRipple(event)` on a ref. Please take a look at [Dropdown](https://github.com/n4kz/react-native-material-dropdown/blob/master/src/components/dropdown/index.js#L232) component for complete example.
