### ISSUE TITLE
Background ripple effect not have opacity when set borderRadius in Android

### ISSUE THREAD

**Issue by thuytony** [n4kz/react-native-material-ripple#24]
Hi. I have a problem with your library. When I set borderRadius for Ripple, is show ok. But when I click in button Ripple, the background animated show black color not implement opacity. Please help me!
Thank you!

**Comment by thuytony** [comment]
Pls help me :(

**Comment by Xammie** [comment]
[this resolved it for me](https://github.com/n4kz/react-native-material-ripple/issues/19)

**Comment by thuytony** [comment]
No no. I mean opacity, not borderRadius.
![2019_03_18_21_07_39_1](https://user-images.githubusercontent.com/34490002/54536055-8841af80-49c2-11e9-8679-b72f037cf6fd.gif)

**Comment by Xammie** [comment]
Could you share your code?
