### ISSUE TITLE
Maintainer Help?

### ISSUE THREAD

**Issue by WrathChaos** [n4kz/react-native-material-ripple#25]
Hello @n4kz,
Do you need a maintainer help for this project? I would like to help and improve the project :) I'm also using this project almost all my projects. You can reach me on Github or email :) 

Thank you for this awesome ripple library :)

**Comment by n4kz** [comment]
Hi!

Thanks for your offer and feedback :) I had not so much time to maintain my RN components during the last year, but now I'm back or at least I hope so. There is not so much work left on this component, but I look forward to see some great PRs or improvement ideas!
