### ISSUE TITLE
Start effect on press down

### ISSUE THREAD

**Issue by lwansbrough** [n4kz/react-native-material-ripple#4]
It's fairly common for Material interfaces to trigger the ripple when the user starts touching the button, and then complete it when they lift their finger. An example of that behaviour can be seen here: http://www.material-ui.com Is this feasible?

**Comment by n4kz** [comment]
This pattern is not so common on mobile devices, as it is on the web. Under the hood `Ripple` component uses `TouchableWithoutFeedback` and supports touch movement after initial touch down event. As a workaround I can suggest using `onLongPress` callback with `delayLongPress` set to reasonably low value.

```javascript
<Ripple onLongPress={() => console.log('on touch start')} delayLongPress={16} />
```

**Comment by Assem-Hafez** [comment]
I think you are right about running the onPress callback on press release. But my intension was to start the ripple animation only on pressing down and the ripple should stay with maximum size till the press is released.

**Comment by n4kz** [comment]
@Assem-Hafez that's completely different effect and I'm not planning to implement it in near future. Probably it should be done as standalone component.

**Comment by Noitidart** [comment]
Aw darn. react-navigation by default implements ripples `onPressIn` of the "back" button. Also on Android the native `<Button>` also starts rippling `onPressIn`. `react-navigation` actually triggers a ripple per second (max of two). Will this not be implemented? :(

**Comment by n4kz** [comment]
As mentioned before, I find maintaining two different behaviours inside one component a difficult task. I'll try to find suitable solution, maybe by creating a fork, but can not promise anything right now.

**Comment by Noitidart** [comment]
Thanks sir for the hopeful reply!! :)

**Comment by vjsingh** [comment]
@n4kz This would be a great addition! Of course I understand if you don't have time to do it. But I think it seems to be a common pattern even on mobile, and it could be good to re-open this issue and see if someone can implement it in this component.

**Comment by vjsingh** [comment]
@n4kz I hacked together a first go at this. Messy, but working

https://github.com/vjsingh/react-native-material-ripple/commit/12e8f8d872ee780caa94e7de8080701e67dc6a9a

**Comment by BtencateSphereon** [comment]
i know this is closed. but  with 0.9.1 the effect still only starts on release? anything i should be doing to make it start on PressIn?
