### ISSUE TITLE
Ripple overflows to the margins as well

### ISSUE THREAD

**Issue by SuhairZain** [n4kz/react-native-material-ripple#5]
When I use margins on a component which has a Ripple as it's direct parent, the ripple overflows to cover the margin as well. This issue is present on both Android and iOS. Attaching a video demo and reproducible code sample.

```jsx
import React from 'react';
import {
    StyleSheet,
    Text,
    View,
} from 'react-native';

import Ripple from 'react-native-material-ripple';

const RippleTest = () => (
    <View style={styles.container}>
        <Ripple>
            <View style={styles.button}>
                <Text>Hello RippleTest!</Text>
            </View>
        </Ripple>
    </View>
);

const styles = StyleSheet.create({
    container: {
        alignItems: 'center',
        flex: 1,
        justifyContent: 'center',
    },
    button: {
        marginBottom: 48,
    },
});

export default RippleTest;
```
![ripple demo mov](https://user-images.githubusercontent.com/5249794/27073023-0a75bcea-5040-11e7-8da3-35618222cd9c.gif)

**Comment by n4kz** [comment]
Thanks for reporting, this is expected behaviour. Margin is set on child component and affects `Ripple` component size.  However margins set on `Ripple` itself are not affected by effect.
