### ISSUE TITLE
Is not getting all TouchableWithoutFeedback props

### ISSUE THREAD

**Issue by scerelli** [n4kz/react-native-material-ripple#7]
If you try to pass  the `testID` as props you will see that it will not be passed down to the touchable.
In this case, for example, you can't use your component inside test to get the `onPress` prop.

**Comment by scerelli** [comment]
PR Here: https://github.com/n4kz/react-native-material-ripple/pull/8

**Comment by n4kz** [comment]
Thanks for PR, merged and released in `0.7.3`.
